name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files on machine
        uses: actions/checkout@v3

      - name: Test build 
        working-directory: ./learn_project
        run: docker build -t  stdlaibach/anime-backend-django:${GITHUB_REF##*/} .

      - name: Check docker images
        run: docker images
