name: Build image

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files on machine
        uses: actions/checkout@v3

      - name: Login to dockerhub
        run: docker login -u stdlaibach ${DOCKERHUB_TOKEN}

      - name: Build image
        working-directory: ./learn_project
        run: docker build -t stdlaibach/anime-backend-django:${GITHUB_REF##*/} .

      - name: Push docker image to private registry
        run: docker push stdlaibach/anime-backend-django:${GITHUB_REF##*/}
